version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: certhub
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
